### ISSUE TITLE
Raise supported minimum java version

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#10]
Currently [JRE 7 is the minimum version](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#requirements) to run OSIAM, but I think we should raise it to JRE 8 to make it possible to use Java 8 features... and [Java 7 is EOL since may 2015](https://java.com/en/download/faq/java_7.xml).

**Comment by tkrille** [comment]
I do like it. Unfortunately, not every OS already ships with Java 8, but I think this is only true for Debian. Any other OS should have Java 8 these days. Seems not that hard to unofficially install Java 8 on wheezy or jessie. So, yeah, let's go for it!

**Comment by tkrille** [comment]
Should we schedule this for 3.0 too?

**Comment by wallner** [comment]
Let's schedule it for 3.0

**Comment by tkrille** [comment]
Already did :-)

**Comment by wallner** [comment]
Do we have a schedule for what we want to go into release 3.0 anywhere?

**Comment by tkrille** [comment]
We have the appropriate milestones in some repos, but not all issues and PRs have been assigned.

**Comment by tkrille** [comment]
In the past the schedule for new releases read like this: All things that will be committed after the last release :)

**Comment by tkrille** [comment]
But seriously, there is the Jira, that roughly contains what will be released. It mostly doesn't contain bug fixes or unplanned changes, like when we resolve stuff from GitHub.

**Comment by wallner** [comment]
I suggest that we start an issue in this repository outlining the major changes that we want to have in the next release. We can also turn the list of the milestones or jira tasks into separate issues to track progress there.

**Comment by tkrille** [comment]
Alright, good idea. Are you doing this?

**Comment by wallner** [comment]
Ok, I would do it. Although I'm now wondering if an issue is the right way to track that. Because we could never close it and would always keep it open. Maybe a Markdown file in this repository or wiki page is more adequate?
Any opinions?

**Comment by tkrille** [comment]
I suggest we make use of [GitHub's milestones feature](https://guides.github.com/features/issues/).

**Comment by wallner** [comment]
Ok, I think we can close that issue. If I recall it correctly , we agreed on raising the minimal required Java version to 8 in the server components and keep the client on 7.

**Comment by tkrille** [comment]
I think, as long as we did not change anything, this issue must be kept open. I suggest, that we use this issue as a meta issue to track the progress in the individual projects.
