### ISSUE TITLE
Pull Request Acceptance Criteria

### ISSUE THREAD

**Issue by fwilhe** [osiam/osiam#106]
I propose that we draft a checklist for acceptance criteria for pull requests. The reason why I would like to have this is simple: Humans tend to forget things, especially the "trivial" things. We can never make sure that this cannot happen, but a curated list of important items may help.

Proposed items on the list:
- Tests are ok with the change _(we might lack documentation on how to do this properly)_
- The commit has a good message [reference1](http://chris.beams.io/posts/git-commit/), [reference2](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message)
- If anything documented was changed: Documentation is aligned with the changes of exactly this PR
- If anything (potentially) user-relevant was changed: `CHANGELOG.md` is updated

Open question: Where to put this list?
- Repository under `docs` (and if so, which repo? all?)?
- Wiki

I would love to have such a hint for this file in the PR-view, as it is there in the issues-view for `CONTRIBUTING.md`, but I don't think that github has this feature.
![screenshot from 2016-01-04 19-42-06](https://cloud.githubusercontent.com/assets/2292245/12097304/46a9e18c-b31b-11e5-8844-6621d66295ec.png)

What do you think about that? Are there items you would like to add/remove/change?

**Comment by wallner** [comment]
I worked in a company once that tried to establish such a checklist and it added unnecessary baggage to the development of the software, slowing the speed down considerably. Mind you, I'm not completely opposed to adding checklist, to the pull requests, but I don't think that we have a problem with the lack of diligence on the part of the reviewers at this point. We did have a few problems with keeping the change logs from time to time, I'll agree to that, I just don't think that this would warrant the introduction of a formalized process. In general I'm of the opinion that it's a bad idea to introduce processes as long as they are not needed.

**Comment by tkrille** [comment]
First of all, I don't understand this to be a formal process, but only some kind of mental help. But I do see the danger, that someone could see it like that. I must confess, that I sometimes forget to check some aspects of a PR. Having a list of stuff that **MAY** be checked, would increase my certainty when reviewing PRs. I don't think we need it on top of every PR. Just put it somewhere, where we can store internal documentation. The wiki seems to be a good place, because it would physically distinguish between internal documents (wiki) and user facing documents (repo).

Why not try it out? If it sucks, we can still revert our decision.

**Comment by tkrille** [comment]
Regarding the items that the checklist should contain, here are some additional thoughts:
- the PR or its single commits fulfill the promised change
- Code style is good enough
- Beware of possible security implications

**Comment by fwilhe** [comment]
> - the PR or its single commits fulfill the promised change

:+1: 

> - Code style is good enough

IMHO, this is too vage. I like the intention of this proposal. It should include link(s) to styleguids, and other related documents. Or maybe just a short sublist of "don't do this" items, as quick reminder. From my personal view, code style is amongst the first things I look at, so I am not sure if this is a too useful item, but your view may vary.

> - Beware of possible security implications

Not too bad for project concerning security :) This definitely needs further links explaining the most common pitfalls in this area.

**Comment by tkrille** [comment]
> > Code style is good enough
> 
> IMHO, this is too vage. I like the intention of this proposal. It should include link(s) to styleguids, and other related documents. Or maybe just a short sublist of "don't do this" items, as quick reminder.

Yes, it should be vague and only contain the common steps, but not the exact criteria. Our recommended code style is well documented in the contributing guidelines, which every main contributor  is aware of.

> From my personal view, code style is amongst the first things I look at, so I am not sure if this is a too useful item, but your view may vary.

The list should contain all items that **MAY** be checked. This includes code style.

> > Beware of possible security implications
> 
> Not too bad for project concerning security :) This definitely needs further links explaining the most common pitfalls in this area.

I don't think we need links at all (except for the excellent articles about commit message writing you mentioned above). Every main contributor should be able to find the relevant information by themselves or by asking here. But feel free to include links to OWASP top 10 and stuff.

Again: I see this suggestion as mental help not a formal process everyone must adhere to. I mean, if you wouldn't have brought this up here, I maybe had created such a checklist myself as a Gist.

**Comment by tkrille** [comment]
As nothing happened here so far, I'll close it.
