### ISSUE TITLE
Add a guide for contributors

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#11]
Should contain:
- how to report bugs
- how to check out and build the projects
- how to use forks and pull requests
- more?

**Comment by tkrille** [comment]
- formal guidelines
- coding style

**Comment by tkrille** [comment]
This is the coding style currently used:

[Code Conventions for the Java Programming Language](http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html) with the following exceptions:
- line width of 120 chars
- indentation with 4 spaces, NO tabs

Here's a formatter definition for the Eclipse IDE: https://gist.github.com/tkrille/46e284a17c744243bc20

Something I forgot? Then add it! :)

**Comment by wallner** [comment]
"The master branch on Github is read-only, every change that gets added to it has to be reviewed in a Github pull request. By following this procedure we can assure a certain level of code quality.

If you feel for some reason that you are unable to adhere to this rule please consider to at least file a bug report or change request so your issue does not get lost and can be fixed or discussed by other OSIAM developers."

**Comment by wallner** [comment]
Formal guidlines means what exactly?

**Comment by tkrille** [comment]
> @wallner: Formal guidlines means what exactly?

For example, that contributors have to use their own fork, no private branches in the upstream repo, read-only master branch, "good" commit messages, etc.

**Comment by wallner** [comment]
Ok, let's see what we can come up with

**Comment by wallner** [comment]
Should this issue not be closed now?

**Comment by tkrille** [comment]
I'm missing the stuff about [coding conventions](https://github.com/osiam/osiam/issues/11#issuecomment-119870881). Can you add this as well?

**Comment by wallner** [comment]
Ok, I will do that.

**Comment by tkrille** [comment]
Re-opened, because the new file has to be distributed among all repos. @wallner can you please do this now?

**Comment by tkrille** [comment]
This is completely done now. Thanks to everybody!
