### ISSUE TITLE
allow only https connections

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#12]
Moved from [Jira](https://jira.osiam.org/browse/STUFF-55):

> At the moment you can run OSIAM with and without an https connection.
> For testing this is ok but in production only https connections should be allowed.
> 
> The idear is to allow http with an flag in the config file. The default should be that only https is allowed. With this it is possible to configure OSIAM for http but every developer has been pointed to the risk.

**Comment by timopick** [comment]
Most times the SSL encryption is handled by a dedicated Webserver. Should we really care about SSL in the osiam endpoints?

**Comment by wallner** [comment]
I think it is a good idea to  inform the user about a wrongly configured web server. We could discuss however if we need to do that with every request. Maybe a big, fat warning at startup would be enough.

**Comment by tkrille** [comment]
Ok, I have to admit, that I just blindly copied this over from Jira without putting much thought in it. Now, as there is a discussion, I started to think about it and came to the following thoughts:

@timopick is right, that most deployments today are using a dedicated Apache or nginx for TLS demarcation. But running OSIAM without one must also be securely possible.

@wallner It's complicated to figure out on startup, if there is a TLS demarcation server in front of OSIAM. But, AFAIC, the current solution - printing a warning in the logs on each non-TLS request - is not viable.

And here comes the "but":

OSIAM has nothing to do with TLS and it cannot even force or activate it on its own. Our current way of deployment is using Tomcat. In this case one has to setup the Tomcat itself to use TLS. When we successfully migrated to Spring Boot, then everything will be "configured via Spring Boot" (actually, the embedded servlet container will be configured). This should work almost out-of-the-box, but we should verify this assumption.

**Comment by wallner** [comment]
After spending some more thoughts on this I think I came to agree with @tkrille It is not OSIAMs business to ensure that incoming connections make use of TLS. I think we should make it very clear in the documentation that it is recommended to run OSIAM over SSL but leave it to the user to take care of that without reminding him three times every single request that he should use SSL.

My suggestion ist to remove the `SSLRequestLoggingFilter`.

**Comment by tkrille** [comment]
+1

**Comment by tkrille** [comment]
Nobody had any objections against this, so we will remove the `SSLRequestLoggingFilter` (osiam/resource-server#79).

**Comment by tkrille** [comment]
And enhance the documentation (#39).
