### ISSUE TITLE
Codacy

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#136]
Currently all issues found by codacy commented by @wallner 's github user. This is because @wallner created the OSIAM organization at codacy. I think we should create a github user 'codacy' or something similar (or the already created osiam-ci user?) and [transfer the codacy organization ownership to this user](https://docs.codacy.com/docs/how-do-i-transfer-an-organization-on-codacy). 

What I do not like with codacy: A synchronization of the osiam organization like circleci did is not possible. The drawback is that all github users which are in the osiam organization in GitHub need to be manually add to the codacy osiam organization, but thats a conceptual problem of codacy. Maybe I do a skype chat with Jaime from Codacy (he invited me in a welcome email ;) ).

**Comment by dacrome** [comment]
After I got feedback from codacy, that there is no way to use a Bot or a by codacy created GitHub user to comment issues, we should now decide how we deal with it.

My suggestion is to create a `codacy` user who is the owner of the OSIAM organization on codacy and who make the issue comments. What do you think?

**Comment by tkrille** [comment]
Isn't there any other way to make a user the target for these comments? Is
it always the owner, who does the commenting?

I would refrain to name this user `codacy`. It might get in the way of
Codacy's plans. After all this user would be totally unrelated to the
company Codacy. What about the idea to let osiam-ci make the comments?

**Comment by dacrome** [comment]
> Isn't there any other way to make a user the target for these comments? Is it always the owner, who does the commenting?

No, there is a integration settings page (e.g. for https://www.codacy.com/app/OSIAM/osiam/settings/integrations) for every repo/project in codacy. The user who is creating the integration is the one who is commenting. 

> I would refrain to name this user `codacy`. It might get in the way of Codacy's plans. After all this user would be totally unrelated to the company Codacy. What about the idea to let osiam-ci make the comments?

Yes, but codacy is the tool which found and comment the issues. You will get notifications in form of `Comment by codacy` which is right I guess. But I'm ok with the `osiam-ci`.

**Comment by dacrome** [comment]
Ok, let's use the `osiam-ci` to make the comments in GitHub

**Comment by dacrome** [comment]
I switched all projects to the osiam-ci user
