### ISSUE TITLE
Change namespace for configuration properties in YAML config?

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#138]
After switching to YAML and having OSIAM_HOME in place, I wondered, whether the current namespace for configuration properties is a good choice. Currently we are using `org.osiam.*` for the ordinary properties, but there's also `osiam.home` (or `OSIAM_HOME`) for the special home directory. I really don't like special treatment of such things, so I'd suggest that we change the namespace from `org.osiam.*` to `osiam.*`. That's also more aligned with Spring Boot, because they use `spring.*` and not `org.springframework.spring-boot.*` (or whatever). I don't see any chance of a naming collision either. 

What do you think?

**Comment by wallner** [comment]
I think we can drop the `org.` from the namespace. We should go for it,

**Comment by dacrome** [comment]
+1 for removing `org.`
