### ISSUE TITLE
Validate schema of incoming resources

### ISSUE THREAD

**Issue by wallner** [osiam/osiam#142]
The merge of pr #134 disabled the validation of the schema resources. To be SCIM compliant we need to validate the schemas again.

**Comment by wallner** [comment]
A viable solution is to implement a custom validator that makes sure that the list of schemas of a `Resource` contains the respective schema. I would like to add an abstract method like

```
abstract public String getSchema();
```

or something like that to the abstract `Schema` class that returns the Schema of the resource as String, that would enable us to write a relatively simple class validator.

**Comment by tkrille** [comment]
I would name the new abstract method `getCoreSchema()` to avoid confusion with `Resource#getSchemas()`. But why even add a new abstract method? We can also configure the schema to check on the annotation, like this:

``` java
@ValidCoreSchema(User.SCHEMA)
public class User {
    // ...
}

@Constraint(validatedBy = { ValidCoreSchemaValidator.class })
// ...
public @interface ValidCoreSchema {
    String value();
    // ...
}

public class ValidCoreSchemaValidator implements ConstraintValidator<ValidCoreSchema, Resource> {
    // ... find ValidCoreSchema#value() in Resource#getSchemas() to validate the Resource
}
```

(The names are just explanatory and not well-thought)

**Comment by wallner** [comment]
Yes, that's an idea too and easier to implement than my original one, because it doesn't need additional methods in the SCIM Resource. However, your solution needs to the schema to validate against to be provided, but I think that's negligible disadvantage. I'm going to come up with a PR today.

**Comment by tkrille** [comment]
Both solutions have their tradeoffs :)
