### ISSUE TITLE
SSL Certificate for osiam.org expired

### ISSUE THREAD

**Issue by wallner** [osiam/osiam#155]
The SSL certificate for https://www.osiam.org  expired  January 15 (almost six weeks ago) creating a nasty browser warning when accessing the site. This is a little embarrassing for a project that might be security relevant.

**Comment by tkrille** [comment]
Maybe it's also @tpick to assing it to?

**Comment by timopick** [comment]
I got it. I will continue pestering the sysops.

**Comment by timopick** [comment]
New certificate is up.

**Comment by dacrome** [comment]
Thanks!
