### ISSUE TITLE
importing project to myEclipse 

### ISSUE THREAD

**Issue by ohoho7** [osiam/osiam#16]
i've cloned those projects:
sudo git clone https://github.com/osiam/resource-server.git
sudo git clone https://github.com/osiam/auth-server.git
sudo git clone https://github.com/osiam/addon-self-administration.git
sudo git clone https://github.com/osiam/addon-administration.git

after importing them to workspace in myeclipse (Version: 2015 Stable 2.0 Build id: 13.0.0-20150518), only addon-adinistration has no errors, I found that there is a bug (in myEclipse? ) when i am importing there are wrong build paths, f.e myEclipse is making packages (for resource-server) main.java.org.osiam... instead of org.osiam... 

I manually changed those packages, but there still is a lot of errors with lack of jars from .m2 dir.
After repairing this there are still errors in eclipse with classes with underscore at the end of name and MetricRegistry, and MetricsModule, and some couple more...

How can I import projects to myEclipse to have no errors after import? (I am doing it by Import Existing Maven Project)

**Comment by tkrille** [comment]
Hello @ohoho7,

thanks for your interest in OSIAM. I personally don't use Eclipse anymore, but I remember a bunch of strange behavior when it came to Maven projects. I'm glad that you fixed most of them. Nevertheless, I'll try to help you with that.

The classes with the underscore at the end are coming from the Hibernate meta model. Please try to generate them by invoking Maven on the command line with the goal compile, i.e.

```
mvn compile
```

Please, also do this with each of the other projects. If Maven can compile everything, then it's definitively an issue with your Eclipse installation. In this case I'll try it myself or better find an Eclipse user on our team. If Maven cannot compile a project, then please provide the output of the Maven process (e.g. as a [Gist](https://gist.github.com/)) here and also your Java and Maven version and kind of OS and version.

**Comment by ohoho7** [comment]
OK, thanks for being ready to help, I found working and simple sollution, before import project need to execute:
mvn eclipse:clean
mvn eclipse:eclipse
and everything is ok

**Comment by tkrille** [comment]
Good to hear that! Have fun with OSIAM. We're looking forward to see your
first Pull Request :)

2015-07-29 12:58 GMT+02:00 ohoho7 notifications@github.com:

> OK, thanks for being ready to help, I found working and simple sollution,
> before import project need to execute:
> mvn eclipse:clean
> mvn eclipse:eclipse
> and everything is ok
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osiam/osiam/issues/16#issuecomment-125919468.

## 

Thomas Krille
Softwareentwicklung
tarent solutions GmbH

Telefon +49 (0) 30 555785-128
Telefax +49 (0) 228 54881-235
t.krille@tarent.de

Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-0 • Fax: +49 228 54881-235
HRB AG Bonn 5168 • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander
Steeg

**Comment by tkrille** [comment]
@ohoho7 reports that the issues have been fixed.
