### ISSUE TITLE
Don't mess around with the scopes of the add-ons' OAuth clients in database migration

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#166]
I think we should remove the [migration of the add-ons' clients' scopes](https://github.com/osiam/osiam/blob/master/src/main/java/db/migration/V2__replace_old_scopes.java#L51). In the latest version of the add-ons we've already dropped support for the old scopes, so users had to do the migration anyway by now. As we will only support a migration from the latest version of OSIAM and all it's components, we can safely remove the Flyway migration.

**Comment by tkrille** [comment]
Has anyone an opinion on this? Otherwise I'll just create the PR :)

**Comment by wallner** [comment]
Go ahead.
