### ISSUE TITLE
Add support for H2 database

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#168]
For simple setups and just to get started quickly, we should support a file-based H2 database. We could store the file under `$OSIAM_HOME/data/osiam.db` (or whatever file extension H2 uses). The H2 database would also be used in the default configuration, so that one doesn't even need to configure anything to get started with OSIAM. This could also be helpful for the Docker image. I'd like to see this in 3.0, as it's fully aligned with one of the goals of OSIAM 3.0: making setup less complicated.

**Comment by wallner** [comment]
I agree, it's something that we should provide with 3.0

**Comment by tkrille** [comment]
Blocked by #172
