### ISSUE TITLE
Deployment of osiam.war

### ISSUE THREAD

**Issue by rakeshrangappa** [osiam/osiam#171]
I have been working on setting up osiam server. There is one particular issue i am facing with "Intialize the Home Directory from Command Line" section as given in the documentation(https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md). I am unable to find osiam.war in order to run the command. Please help me overcome the issue.

**Comment by dacrome** [comment]
Hi @rakesh30892,

first you need to clone the sources with `git clone https://github.com/osiam/osiam.git`.
I you do not have `git` installed, you can [download the current sources](https://github.com/osiam/osiam/archive/master.zip) and unpack the zip.
After cloning or downloading, switch to the sources directory and run `mvn clean package` to build the war file. Then you can run `java -jar osiam.war initHome --osiam.home=/var/lib/osiam`.
I you do not have maven installed you can download the latest snapshot [here](https://maven-repo.evolvis.org/snapshots/org/osiam/osiam/3.0-SNAPSHOT/).

Have fun with OSIAM.

**Comment by rakeshrangappa** [comment]
Hi @dacrome ,
Thanks a lot !

**Comment by dacrome** [comment]
Glad that I could help you. If you have any other question, do not hesitate to create a new issue.
