### ISSUE TITLE
Login Credentials to generate Authorization Code

### ISSUE THREAD

**Issue by rakeshrangappa** [osiam/osiam#174]
Hi, I have created a client and I want to generate an Authorization code via hitting the URL as mentioned in the documentation. This leads to a login page. I am stuck as to what credentials are supposed to be provided for the new client.

**Comment by dacrome** [comment]
Hi @rakesh30892,

you can not login with a client with it's id and secret. You can only login with a user (username and password). If you have a default installation of osiam, just try it with the user `admin` and password `koala`.

This is the case of the 3-legged OAuth flow, where the client application uses the authorization code to get an access token of the user to avoid to release the password of the user.
Twitter has a nice description of the [3-legged OAuth flow](https://dev.twitter.com/oauth/3-legged) and we also provide a description of our [authorization code grant](https://github.com/osiam/osiam/blob/master/docs/OSIAM-Overview.md#authorization-code-grant).

**Comment by rakeshrangappa** [comment]
Hi @dacrome, thanks for responding but the clarification I required was regarding the credentials, i.e. whether the default username and password can be updated and used to generate as in, can i update "admin/koala" to something else and login ?

**Comment by tkrille** [comment]
If you just want change the admin user via the command line, please see the [documentation on this](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#customize-setup).

**Comment by dacrome** [comment]
@rakesh30892 did our explanations help? If so, please close this issue.

**Comment by rakeshrangappa** [comment]
Hi, Thanks for the help !
