### ISSUE TITLE
Add "Easy Hack" Label for Issues

### ISSUE THREAD

**Issue by fwilhe** [osiam/osiam#18]
LibreOffice has the concept of "easy hacks" for issues, that are suitable for new contributors. I think it would be a good idea to introduce a label for issues that are considered such a task. What do you think about that idea?

**Comment by wallner** [comment]
I like the idea of such a label although I don't approve of the name because it implies "hackineness" maybe we could call it "low hanging fruit"?

**Comment by fwilhe** [comment]
I guess it depends on your understanding of the term "hack". But yes, "low hanging fruit" is ok for me, too.

**Comment by tkrille** [comment]
+1, who will manage to create all these labels? Is there some shortcut?

**Comment by dacrome** [comment]
+1

**Comment by dacrome** [comment]
I do it.

**Comment by tkrille** [comment]
@dacrome checkout this: https://www.npmjs.com/package/github-label-manager

**Comment by fwilhe** [comment]
What is the status? The label is created, but what about all the existing issues? Does someone (of the experienced contributes) want to assign this tag to suitable ones? Can we close this issue then?

**Comment by dacrome** [comment]
I added "low hanging fruit" label in every repo. We should create a new issue if we like to discuss which labels should be used and synced in all repos.
