### ISSUE TITLE
Attribute filters on all resources

### ISSUE THREAD

**Issue by wallner** [osiam/osiam#182]
RFC [7644](https://tools.ietf.org/html/rfc7644#section-3.9) states in section 3.9:

> For any SCIM operation where a resource representation is returned  (e.g., HTTP GET)
> [...] Clients MAY request a partial resource representation on any operation that returns
> a resource within the response by specifying either of the mutually exclusive URL query
> parameters "attributes" or "excludedAttributes"

At the moment we only support attribute filtering for the search query. We need to at least support the `attributes` filtering for resources with `GET`on the Group and User resources.

**Comment by tkrille** [comment]
@wallner I assume, that the last doing for this one, is to extend the API in the connector to filter for attributes. Is this right or has anything still to be implemented in the server?

**Comment by wallner** [comment]
The server is done and merged.

**Comment by tkrille** [comment]
I've created an issue for the part in the connector: https://github.com/osiam/connector4java/issues/220

**Comment by tkrille** [comment]
So this issue is done and gets closed.
