### ISSUE TITLE
Standalone Application Deployment in Production?

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#190]
The standalone application deployment will be the new recommended way to run OSIAM. While running OSIAM with `java -jar` on the command line might be a viable way for testing or running in containers, but what about running in a production environment without containers? Shouldn't we supply some startup scripts, i.e. SysVinit scripts or systemd units? How is an admin supposed to easily run OSIAM in production? I think the ["detailed reference installation"](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md) is supposed to be the guide about that, but what should we put there regarding standalone application deployment?

Part of #69

**Comment by tkrille** [comment]
[Fully executable JARs](http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-install) are looking promising. The rest on this page also provides some ideas.

**Comment by tkrille** [comment]
Another thought: We can use the home directory and populate it with a start script under `$OSIAM_HOME/bin/osiam(.sh|.bat?)`. We could also copy to war file to `$OSIAM_HOME/bin/` and reference it from the start script. Similar, we could put ready to use init scripts and unit files somewhere in the home directory. Much like OSIAM would extract itself (or its distribution archive) when running the first time (or starting with `initHome` command).

**Comment by tkrille** [comment]
A fully executable WAR is awesome. I've prepared a PR for this: #191. But this doesn't completely solve the question. What about init scripts and service units and whatever init systems being used?

**Comment by wallner** [comment]
Init script and service units are not our responsibility and nothing we should worry about, after all, there are just too many different systems to support them all. I clearly see this as a task for people packaging up OSIAM for their operating systems or distributions. I don't really see a need for action in the core here.

**Comment by tkrille** [comment]
Alright, fair enough. But I think we should at least copy the stuff from [Spring Boot's own documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-service) on this topic.

**Comment by tkrille** [comment]
I mean: We should put this in our own documentation :)

**Comment by dacrome** [comment]
+1 for putting it in our documentation. But wouldn't this make #64 (Build Debian packages in this repo) obsolete?

**Comment by tkrille** [comment]
No, it wouldn't. We can still package OSIAM by ourselves some time. This issue is just about making recommendations on how to run OSIAM.

**Comment by wallner** [comment]
Ok, I agree about copying the pieces from the Spring boot documentation. I am considering to start an OSIAM manual and that would definitely be the place for it.

**Comment by tkrille** [comment]
Then we maybe should coordinate @wallner. I've just asked this question, because I wanted to start writing the docs about running standalone in production (the last part of #69).

**Comment by dacrome** [comment]
Then please add it. We forget about it when we won't do it now.

**Comment by tkrille** [comment]
It's part of #69 which is scheduled for 3.0. Why should we forget it?
