### ISSUE TITLE
Deploy releases to Bintray

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#194]
This is the meta issue to discuss the concept on how to release the OSIAM components to Bintray. I will create a doing issue in every repository which should be released on Bintray.
- We already discussed offline that it would be a good idea to use CircleCI instead of our internal Jenkins.
- And how should we release with maven? The concept of maven release plugin is a little bit outdated and not usable with CircleCI I think.
- How to trigger the release on CircleCI?

**Comment by dacrome** [comment]
> We already discussed offline that it would be a good idea to use CircleCI instead of our internal Jenkins.

I vote for CircleCI.

> And how should we release with maven? The concept of maven release plugin is a little bit outdated and not usable with CircleCI I think.

I think we need a prepare release commit with a CHANGELOG cleanup and a commit that bumps the snapshot version. The release version is set within the release process on the fly with the maven versions plugin. Can this be automated with CircleCI?

> How to trigger the release on CircleCI?

If this current commit is tagged? Or some flag in the commit message?

**Comment by tkrille** [comment]
> We already discussed offline that it would be a good idea to use CircleCI instead of our internal Jenkins.

Yes, CircleCI

> And how should we release with maven? The concept of maven release plugin is a little bit outdated and not usable with CircleCI I think.

This is really easy (in theory). Suppose we want to release version 3.0, then this has to be done:
1. The master branch must be fully ready to be released, e.g. complete changelog, clean POM (Version in POM is `3.0-SNAPSHOT`).
2. The person responsible for the release creates a new tag `3.0` and pushes it upstream.
3. Circle CI notices that and start to build the Tag. Actually, we have to first configure that in the `deployment` section of the `circle.yml`. I asked some of the support people some time ago about building tags, and it seemed very easy to do so.
4. Our Circle CI build script will detect, that it is building a tag and not a branch or PR.
5. The build script changes the version within the POM to the tag, i.e. `3.0`.
6. The build runs normally and eventually deploy the release artifact to Bintray.
7. The build script increases the version in the POM from `3.0-SNAPSHOT` to `3.1-SNAPSHOT`, commits the change und pushes it upstream (this can also be done by the person responsible for the release).

> How to trigger the release on CircleCI?

Pushing a tag will do the trick. In fact, what really makes a release? The answer is: a tag in Git. That's the source and the trigger.

**Comment by dacrome** [comment]
Awesome explanation. Thanks @tkrille. I found a [great blog post](http://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/) from bintray how to deploy releases to bintray and maven central.

**Comment by dacrome** [comment]
> Circle CI notices that and start to build the Tag. Actually, we have to first configure that in the deployment section of the circle.yml. I asked some of the support people some time ago about building tags, and it seemed very easy to do so.
> 
> Our Circle CI build script will detect, that it is building a tag and not a branch or PR.

Yes, it's easy to listen to a new git tag on CircleCI: https://circleci.com/docs/configuration#tags.

**Comment by tkrille** [comment]
@wallner and I had the idea to test the new release process with some release candidates.

**Comment by dacrome** [comment]
We can do it, but we do not need to because the uploaded releases to bintray are only in a published state before we can finally release them. Checkout the above mentioned blog post.

**Comment by tkrille** [comment]
But we wouldn't get rid of the tags on GitHub.

**Comment by dacrome** [comment]
We can test it in our forks.

**Comment by tkrille** [comment]
But release candidates have the advantage, that we can get early feedback from the community :)

**Comment by tkrille** [comment]
I really want to release them all the way down to Maven Central, GitHub Release pages and the blog, etc.

**Comment by tkrille** [comment]
I think for SNAPSHOTS we also need some place where we can just place the latest SNAPSHOT under the same name every time, e.g. `osiam-latest.war`.

**Comment by tkrille** [comment]
But SNAPSHOTS and releases must still be put on the central (or any other public maven repository), because the ITs consume them from there.

**Comment by tkrille** [comment]
Idea:

We put SNAPSHOTS on OSS JFrog (Maven repo) and also on a plain Bintray folder, where it can be downloaded under the name `osiam-latest.war`. We will overwrite this file on Bintray with every build on CirclCI.

Releases can be put on a Bintray release repo (Maven repo) and also in the same plain Bintray folder for convenient download under the release name, i.e. `osiam-3.0.war`. It would also be nice to upload releases straight to GitHub Releases, too, but this can be implemented later. It's no big deal to do this manually.

**Comment by tkrille** [comment]
This seems to be done?

**Comment by dacrome** [comment]
No. We need to finish it for the connector. But we can create a doing issue in the connector repo.

**Comment by dacrome** [comment]
Done: https://github.com/osiam/connector4java/issues/215
