### ISSUE TITLE
Should we use commit tags?

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#20]
I don't think we need them, because the commit message should already be [meaningful as possible](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message).

**Comment by fwilhe** [comment]
I agree that we can omit the tag, but this design decision should be documented so that every (potential) committer knows about it. It should go into CONTRIBUTING.md, I guess.

**Comment by tkrille** [comment]
No, don't use them.

> I agree that we can omit the tag, but this design decision should be documented so that every (potential) committer knows about it. It should go into CONTRIBUTING.md, I guess.

I don't think we have to do this. Using a tag in the commit summary is something you would explicitly enforce, not deny.

**Comment by fwilhe** [comment]
> I don't think we have to do this. Using a tag in the commit summary is something you would explicitly enforce, not deny.

I prefer explicit rules over implicit ones, but if everyone is fine with potential contributes using tags (if they are used to do so), then this is ok with me.

**Comment by dacrome** [comment]
So, maybe the commit messages should be more addressed in the [pull requests section](https://github.com/osiam/osiam/blob/master/CONTRIBUTING.md#pull-requests)?

**Comment by wallner** [comment]
I would leave that out of `CONTRIBUTING.md` for now. Let's not add too high a bar to get over if you want to get your contribution into OSIAM. If it turns out to be a problem we can change that later.

**Comment by dacrome** [comment]
Ok

**Comment by tkrille** [comment]
ACK
