### ISSUE TITLE
generated-sources/apt not being detected as a source directory when importing into eclipse

### ISSUE THREAD

**Issue by tkent** [osiam/osiam#200]
The hibernate JPA DDL  generated sources are not added to an eclipse project when importing. This is caused because there is no configuration in the POM to add them. It's easy to reproduce, just import the project using the POM in eclipse and notice all of the Entity_ classes cannot be found.

A fix would be to use the build-helper-maven-plugin so eclipse is aware of the sources. I'll submit a pull request later in case you're interested in just doing that.

**Comment by dacrome** [comment]
I think this issue can also be closed, right @tkent?

**Comment by tkent** [comment]
@dacrome 

Sorry for the slow response - yes, absolutely.
