### ISSUE TITLE
Enable filtering for all resources with GET method

### ISSUE THREAD

**Issue by wallner** [osiam/osiam#202]
In [section 3.9](https://tools.ietf.org/html/rfc7644#section-3.9) the scim spec states:

>   Clients MAY request a partial resource representation on any
>  operation that returns a resource within the response by specifying
>   either of the mutually exclusive URL query parameters "attributes" or
>  "excludedAttributes"

I suggest that we add the filtering of attributes to the `/Users`, `/Groups` `/Me` endpoints if they get called with the with the `GET` operation. At the moment we are only supporting `attributes` filtering. I suggest that we add `excludedAttributes` filtering too, it's not too hard and should be scheduled for the 3.0 release.

**Comment by wallner** [comment]
Oh! Silly me! I just realized that I already filed a duplicate [bug](https://github.com/osiam/osiam/issues/182), I think that this one here has a little description that is a little better than in the other one, so I'll just leave it open for now.

**Comment by dacrome** [comment]
I think this is done now, right?

**Comment by tkrille** [comment]
We need an issue for `excludedAttributes` … one moment

**Comment by tkrille** [comment]
https://github.com/osiam/osiam/issues/236

**Comment by tkrille** [comment]
Yes, it's done.
