### ISSUE TITLE
Simple OSIAM Docker Image

### ISSUE THREAD

**Issue by burberius** [osiam/osiam#206]
I created a simple OSIAM Docker image, that just includes the auth-server and the resource-server. It uses an external postgresql server (docker).

https://hub.docker.com/r/burberius/osiam-simple/

Source:
https://github.com/burberius/osiam-docker-simple

Perhaps it's useful for other users and you could link to it.

**Comment by tkrille** [comment]
I'm sorry, but this one got lost due to the release of OSIAM 3.0. Also, OSIAM 2.x has been discontinued with the release of 3.0. If you like, you can participate in building the new OSIAM 3.0 Docker image. We're currently planning the details and there will be an issue for this doing soon.
