### ISSUE TITLE
Remove PATCH'ing of resources

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#21]
At this time, we only implement the old PATCH API, the predecessor of the current JSON PATCH based API. It appears to me, that we don't really want to migrate to the new PATCH API right now, basically because of the high efforts that come with this undertaking. Due to this, I propose that we deprecate and eventually remove the old PATCH API. This way we also get rid of the not-so-beloved UpdateUser/Group. Components that have to be changed to achieve this:
- OSIAM
- connector4java
- addon-self-administration
- addon-administration (?)
- ITs and all other tests

So in fact, almost every component has to be changed!

**Comment by wallner** [comment]
I think though it should be done none the less. The `UpdateUser` and `UpdateGroup` are really unwieldy and need to go. Since our old PATCH API is out of date we should retire it.

So I vote for it.

**Comment by tkrille** [comment]
I've created a bunch of PRs, that remove the usage of PATCH from the Add-Ons and the ITs, and deprecate PATCH in the connector: https://github.com/osiam/connector4java-integration-tests/pull/342, https://github.com/osiam/addon-administration/pull/137, https://github.com/osiam/addon-self-administration/pull/179, https://github.com/osiam/connector4java/pull/210

**Comment by dacrome** [comment]
So I can remove PATCH from OSIAM now?

**Comment by tkrille** [comment]
Apparently, yes.

**Comment by tkrille** [comment]
Oh, this is still blocked by https://github.com/osiam/connector4java-integration-tests/pull/342

**Comment by tkrille** [comment]
https://github.com/osiam/connector4java-integration-tests/pull/342 is done, so go for it!
