### ISSUE TITLE
Could not resolve placeholder 'osiam.db.driver' in string value "${osiam.db.driver}"

### ISSUE THREAD

**Issue by harikrishna553** [osiam/osiam#218]
I am working in setting up osiam server, MySQL as backend. I am stuck with following error. Any help on this....

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String org.osiam.configuration.DatabaseConfiguration.driverClassName; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'osiam.db.driver' in string value "${osiam.db.driver}"

Following are the steps, I followed.
1. git clone https://github.com/osiam/osiam.git
2. Update osiam.home in context.xml

<Context>
    <Environment name="osiam.home" value="/Users/harikrishna_gurram/" type="java.lang.String"/>
</Context>
1. Update tomcat heap size: catalina.sh
   export CATALINA_OPTS="-Xms512M -Xmx1024M"
2. Create database osiam and use named osiam
   mysql> create database osiam;

Create a user and grant permissions
CREATE USER 'osiam'@'localhost' IDENTIFIED BY 'osiam';
GRANT ALL PRIVILEGES ON \* . \* TO 'osiam'@'localhost';
1. Updated ./src/main/resources/home/config/osiam.yamlfor MySQL configurations and commented H2 database configurations.
   
   vendor: mysql
     driver: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost/osiam
     username: osiam
     password: osiam
2. Generated war file.
   /Users/harikrishna_gurram/Downloads/apache-maven-3.3.9/bin/mvn clean package
3. Deployed war file in tomcat.

**Comment by tkrille** [comment]
Duplicated by #219
