### ISSUE TITLE
Address Attribute for user

### ISSUE THREAD

**Issue by rakeshrangappa** [osiam/osiam#221]
Hi ! I am trying to create a user by sending the following attributes as a query.

``` json
{
  "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
  "externalId": "xyz",
  "userName": "user1",
  "displayName": "user1",
  "name": {
    "formatted": "user  name",
    "familyName": "user",
    "givenName": "name"
  },
  "emails": [
    {
      "value": "user@mail.com"
    }
  ],
  "addresses": [
    {
      "streetAddress": "abc",
      "locality": "pqr",
      "region": "ijk",
      "postalCode": "111111",
      "country": "AM",
      "formatted": "abc, pqr, ijk, 111111, AM"
    }
  ]
}
```

I receive the following error:
org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "addresses"

Is this the correct way of sending a JSON Query in order to create a user ?

**Comment by tkrille** [comment]
Hello @rakesh30892,

I took the liberty and formatted the JSON in your initial comment. You've closed the issue, but can you tell us how you solved the it? I'm just curious, because maybe we were not explicit enough in some parts of the documentation. In this case we have to fix the docs.

**Comment by rakeshrangappa** [comment]
Hi @tkrille,
It was an error on my part as i wasn't handling the JSON response correctly in my code. I think the docs are perfect in this aspect. Thanks a lot !
