### ISSUE TITLE
Not getting Resources for all users request

### ISSUE THREAD

**Issue by harikrishna553** [osiam/osiam#222]
Hello,
  I am using OSIAM as SCIM server. I written Jersey client to speak to OSIAM Server. While trying to get all users by hitting the url "http://10.212.143.191:8080/osiam/Users/", I am getting response like {"itemsPerPage":100,"**Resources":[]**,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"startIndex":1,"totalResults":62}. As you see Resources field is empty.

Following are my model classes.

```
@ToString
public class UserResponse {

    @Getter @Setter private Integer totalResults;
    @Getter @Setter private Integer itemsPerPage;
    @Getter @Setter private Integer startIndex;
    @Getter @Setter private List<String> schemas = new ArrayList<>();

    @Getter @Setter private List<User> Resources = new ArrayList<>();   
}

```

```
@ToString
@EqualsAndHashCode(exclude = {"id", "meta", "schemas"})
public class User {

     @Getter @Setter private String id;
     @Getter @Setter private String externalId;
     @Getter @Setter private Meta meta = new Meta();
     @Getter @Setter private Set<String> schemas = new HashSet<>();
     @Getter @Setter private String userName;
     @Getter @Setter private Name name = new Name();
     @Getter @Setter private String displayName;
     @Getter @Setter private String nickName;
     @Getter @Setter private String profileUrl;
     @Getter @Setter private String title;
     @Getter @Setter private String userType;
     @Getter @Setter private String preferredLanguage;
     @Getter @Setter private String locale;
     @Getter @Setter private String timezone;
     @Getter @Setter private Boolean active;
     @Getter @Setter private String password;
     @Getter @Setter private Set<Email> emails = new HashSet<>();
     @Getter @Setter private Set<PhoneNumber> phoneNumbers = new HashSet<>();
     @Getter @Setter private Set<Im> ims = new HashSet<>();
     @Getter @Setter private Set<Photo> photos = new HashSet<>();
     @Getter @Setter private Set<Address> addresses = new HashSet<>();
     @Getter @Setter private Set<Group> groups = new HashSet<>();
     @Getter @Setter private Set<X509Certificate> x509Certificates = new HashSet<>();
     @Getter @Setter private Manager manager;
     @Getter @Setter private String employeeNumber;
     @Getter @Setter private String costCenter;
     @Getter @Setter private String organisation;
     @Getter @Setter private String division;
     @Getter @Setter private String department;

     public User() {
          schemas.add("urn:ietf:params:scim:schemas:core:2.0:User");
     }    
}
```

Following method hit the REST Users endpoint.

```
public Response getAllUsers() {
     WebTarget target = client.target("http://localhost:8080/jersey_tutors/employees");

     return target.request(MediaType.APPLICATION_JSON).header("Content-type", "application/json").header("Authorization", getAccessToken().get()).get();

     }

```

Following method print the response.

```
public static void getUsertest(){
     Response response = service.getAllUsers();

     UserResponse resp = response.readEntity(UserResponse.class);
     System.out.println(JSONUtil.getJson(resp));
}
```

FYI, I am adding debug log.

```
Jun 01, 2016 4:48:33 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > GET http://10.212.143.191:8080/osiam/Users/
1 > Accept: application/json
1 > Authorization: Bearer cad63d9a-4bd2-45eb-8c30-11a401d93ea7
1 > Content-type: application/json

Jun 01, 2016 4:48:34 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 200
1 < Cache-Control: no-cache, no-store, max-age=0, must-revalidate
1 < Content-Type: application/json;charset=UTF-8
1 < Date: Wed, 01 Jun 2016 11:20:20 GMT
1 < Expires: 0
1 < Pragma: no-cache
1 < Server: Apache-Coyote/1.1
1 < Transfer-Encoding: chunked
1 < X-Content-Type-Options: nosniff
1 < X-Frame-Options: DENY
1 < X-XSS-Protection: 1; mode=block

{"itemsPerPage":100,"Resources":[],"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"startIndex":1,"totalResults":62}

```

**Comment by dacrome** [comment]
Hey @harikrishna553,

it's okay to write your own client, but why don't you use the [connector4java](https://github.com/osiam/connector4java) to retrieve the users?

Did you try to retrieve the users with curl? What does it respond?

```
$ curl -i -H "Accept: application/json" -H "Content-type: application/json" -H "Authorization: Bearer $YOUR_ACCESS_TOKEN" -X GET http://10.212.143.191:8080/osiam/Users/
```

Greetz,
David

**Comment by harikrishna553** [comment]
Hello Dacrome,
  Thanks for the reply.  When i tried with advanced rest clinet (Chrome plugin), it is returning all users, but when i used Jersey rest client it is unable to map to UserResponse class.

I can able to solve the problem in different way. I am reading response as  json string and mapping it to my model class UserResponse.

```
/* Get all users from scim server */
Response response = getAllUsers();
String jsonResponse = response.readEntity(String.class);
UserResponse cloudUsersResp = JSONUtil.getObject(jsonResponse,UserResponse.class); 
```

Only thing I am not getting is, why it is unable to map the response directly to UserResponse class. Will you able to suggest on this?

**Comment by tkrille** [comment]
Hi @harikrishna553,

I think you have to explicitly configure Jersey to correctly map a JSON String to some POJO. On the other hand, your debug logs proofs, that the JSON returned from OSIAM does not contain any data in the resources attribute. That's strange. And if you use some other HTTP client, you actually getting a response with some resources in it? That's even stranger. Can you provide a small working app, that's able to always reproduce the issue?

**Comment by harikrishna553** [comment]
Hi Tkrille,
 I figured out the issue. User model class is not matched to the response in resource. I can able to solve the issue by ignoring some multi valued attributes (which are not supported by osiam).

**Comment by tkrille** [comment]
I'm curious: what multi-valued attributes don't we support? AFAIC we support all of them.

**Comment by harikrishna553** [comment]
Attributes like groups, manager, department etc.,

**Comment by tkrille** [comment]
Alright, but to be clear:
- We do support `User.groups`, but not `Group.groups`
- "_manager, department etc.,_" are coming from the enterprise extensions, which we do not support fully, but planning to do so: https://github.com/osiam/osiam/issues/133

Thanks for your additional information.

**Comment by tkrille** [comment]
Oh, I wasn't right at `Group.groups`: That's not supported by the current SCIM spec. But we still support `User.groups` :)
