### ISSUE TITLE
Extend the validity of the GPG signing key

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#228]
Our signing key expires on 2016-07-15. Somebody has to extend it, before this date.

**Comment by tkrille** [comment]
Uh oh, that didn't work out as expected.

**Comment by tkrille** [comment]
Ok, I've extended the keys validity to 2017-07-15, so next year. I've put the key pair on Bintray and uploaded it to tarent PGP server and the SKS key server pools. The updated key is currently propagating through the internet and should be available on each key server within the next hours. Can somebody confirm this and then close the issue please? /cc @wallner

**Comment by dacrome** [comment]
Thanks!
