### ISSUE TITLE
Remove support for old, method-based OAuth scopes

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#23]
This issue is already work in progress and merely exists to track the current status and associated PRs:
- [x] [docs in this repo](https://github.com/osiam/osiam/pull/24)
- [x] [resource-server: support for old scopes](https://github.com/osiam/resource-server/pull/54)
- [x] [auth-server: support for old scopes](https://github.com/osiam/auth-server/pull/60)
- [x] [auth-server: usage of old scopes](https://github.com/osiam/auth-server/pull/60)
- [x] [auth-server: flyway migration to remove old scopes from db](https://github.com/osiam/auth-server/pull/63)
- [x] [addon-self-administration: usage of old scopes](https://github.com/osiam/addon-self-administration/pull/141)
- [x] [addon-self-administration-plugin-example: usage of old scopes](https://github.com/osiam/examples/pull/19)
- [x] [addon-administration: usage of old scopes](https://github.com/osiam/addon-administration/pull/93)
- [x] [example webapp: usage of old scopes](https://github.com/osiam/examples/pull/20)
- [x] [integrations tests: usage of old scopes](https://github.com/osiam/connector4java-integration-tests/pull/269)
- [x] [other test-suites: usage of old scopes](https://github.com/osiam/test-suites/pull/47)
- [x] [OSIAM Shell: usage of old scopes](https://github.com/osiam/shell/pull/8)
- [x] [auth-server: usage of old scopes in tests](https://github.com/osiam/auth-server/pull/65)

**Comment by tkrille** [comment]
More points for the checklist will come step by step.

**Comment by tkrille** [comment]
@dacrome Can you have a look please?

**Comment by dacrome** [comment]
All opened PRs are merged, only two are missing to resolve this issue.

**Comment by tkrille** [comment]
updated

**Comment by tkrille** [comment]
Flyway migrations are ready.

**Comment by tkrille** [comment]
I'm currently not sure if I found all places where we still use the old scopes. Can somebody check this too?

**Comment by tkrille** [comment]
Should be done now.

**Comment by dacrome** [comment]
Awsome! Thanks @tkrille!
