### ISSUE TITLE
Test a full release cycle

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#240]
Ok, now that our release chain seems to be complete. We should test a full release of everything with the next CR. Everyone okay with that? I will do this then.

**Comment by dacrome** [comment]
Sure!

**Comment by tkrille** [comment]
This is now blocked by https://github.com/osiam/connector4java/pull/223 and https://github.com/osiam/addon-self-administration-plugin-api/pull/27

**Comment by tkrille** [comment]
Alright, I'm starting now with `connector4java-1.9.CR1`.

**Comment by tkrille** [comment]
Status update: We have both connector 1.9.CR1 and self administration's plug-in API 1.6.CR1 on the central now: http://search.maven.org/#search%7Cga%7C1%7Corg.osiam

Everything worked as expected (after some minor fixes). The next steps are the add-ons and then we're done with the release test.

**Comment by tkrille** [comment]
Status update: Add-ons have been released:

https://bintray.com/osiam/downloads/addon-administration/1.9.CR2/view
https://bintray.com/osiam/downloads/addon-self-administration/1.9.CR2/view

I'm demoing the new release process tomorrow with OSIAM 3.0.CR2. Everyone's invited to join me. It will be at the office. /cc @wallner @dacrome @fwilhe

**Comment by tkrille** [comment]
BTW: I'll write a small announcement, when everything is done, on the blog.

**Comment by dacrome** [comment]
That's great! Thank you!

**Comment by tkrille** [comment]
When do you guys have time for this?

**Comment by tkrille** [comment]
This was a complete complete success :)

**Comment by tkrille** [comment]
I've written the announcement: https://github.com/osiam/osiam.github.io/pull/7, so this is done now.
