### ISSUE TITLE
osiam/osiam-schema is marked as [DEPRECATED]. What is the replacement?

### ISSUE THREAD

**Issue by berrueta** [osiam/osiam#246]
osiam/scim-schema is marked as [DEPRECATED], but there is no indication of what module should be used instead.

Is there a more up-to-date replacement?

**Comment by tkrille** [comment]
Hi @berrueta,

thanks for your question and your interest in OSIAM. The SCIM schema has been completely merged into the [Connector4Java](https://github.com/osiam/connector4java). The reasons for this have been explained by @wallner in a similar question: https://github.com/osiam/osiam/issues/197#issuecomment-201086938. So, if you just need the SCIM classes in your project, you can simply depend on the [Connector4Java](https://github.com/osiam/connector4java). Having the extra parts of the connector in your project should do no harm. The SCIM part is still nicely separated from the connector part.

**Comment by tkrille** [comment]
I hope I could answer your question. For now I'm closing the issue. Feel free to re-open it, if you have any further questions.
