### ISSUE TITLE
Shut down "ci-osiam.lan.tarent.de"

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#252]
As we moved our complete build infrastructure to the cloud, the old Jenkins at _ci-osiam.lan.tarent.de_ is not needed anymore. We could easily shut it down at this very moment, but there is one little issue to solve first: ci-osiam is the only central place where the PGP key pair of the release key is stored. It's also stored in the key ring on my local machine, and maybe on other developer's machines too. The question now is: Do we need a central place to store the key pair or is it sufficient, if "everybody" stores the key in their local key ring?

**Comment by wallner** [comment]
Let's use something like [Blackbox](https://github.com/StackExchange/blackbox) to manage the credentials.

**Comment by tkrille** [comment]
And put the blackbox into this repo?

**Comment by wallner** [comment]
Yes, either  this repository or the web site's

**Comment by tkrille** [comment]
Do you mean https://github.com/osiam/osiam.github.io with "the web site's"? Then I would rather put it into https://github.com/osiam/osiam.

**Comment by wallner** [comment]
Yes, that's the repository I meant.

**Comment by tkrille** [comment]
Alright, let's put it in https://github.com/osiam/osiam, ok?

**Comment by wallner** [comment]
ok!

**Comment by tkrille** [comment]
One more concern: Is blackbox (and therefore GPG) secure enough to put it on the public internet? I'm concerned about offline attacks, of course.

**Comment by tkrille** [comment]
And: Do we put an non-encrypted version of the release key into the blackbox or an encrypted one and an additional file containing the passphrase?

**Comment by wallner** [comment]
I suggest that we use a file sharing service like [Dropbox](https://dropbox.com) or similar to share the encrypted release key between all entitled developers.

**Comment by tkrille** [comment]
Agreed. Send me your email address and I'll add you to the shared folder. I'll send you the password via email, using the PGP key associated with that address. /cc @dacrome @timopick

**Comment by tkrille** [comment]
Ok, the key is safely stored now. I'll request a shutdown next Monday.

**Comment by tkrille** [comment]
This is done now.
