### ISSUE TITLE
web.xml is missing at osiam.war file

### ISSUE THREAD

**Issue by tusharparate1** [osiam/osiam#254]
Hi Team,
I have downloaded the osiam.war file from https://dl.bintray.com/osiam/downloads/osiam/3.0/
and found that web.xml is missing..

Could you please let me know if I am missing anything here.

Thanks,
Tushar

**Comment by dacrome** [comment]
Hi Tushar,

I think you want to start OSIAM in a servlet container like Tomcat?
If so, please have a look into the [installation guide](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#starting-in-tomcat). Consider that you need a servlet container that support at least Servlet API 3.

Greetz,
David

**Comment by dacrome** [comment]
Hi @tusharparate1,

I close this issue for now. If you have any problems, just re-open this issue.

Regards,
David
