### ISSUE TITLE
Official OSIAM email address

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#262]
I think we need an official email address to register the OSIAM team to services like www.keybase.io or just to receive support requests or even notifications from external services.

Here are some ideas:
- Use the already existing info@osiam.org (Admin ticket!)
- ~~Use the [Slack Email Integration](https://osiam.slack.com/apps/A0F81496D-email) (Thx @tkrille!)~~
- Create a mailing list e.g. with the already existing [OSIAM Google Group](https://groups.google.com/forum/#!forum/osiam)

The mails send to the email address should only accessible by the developers of OSIAM because they may contain sensible data. Maybe we need multiple email addresses to handle different use cases.

Any thoughts on this?

**Comment by dacrome** [comment]
:( the [Slack Email Integration](https://osiam.slack.com/apps/A0F81496D-email) "...is only available to teams on paid plans".

**Comment by dacrome** [comment]
I created an admin ticket to forward all emails from info@osiam.org to @wallner, @tkrille, @tpick and me.

**Comment by tkrille** [comment]
Sounds good to me. Thank you!
