### ISSUE TITLE
The clientEntity id  is limited 32 characters 

### ISSUE THREAD

**Issue by wallner** [osiam/osiam#263]
The client entity id is limited to 32 characters which is unnecessarily short and prevents the usage of, for instance, UUIDs as client names. I suggest raising this limit to at least 256 characters, or drop it all together.

**Comment by dacrome** [comment]
Good catch! Let's do it!

**Comment by tkrille** [comment]
+1

**Comment by tkrille** [comment]
Added to 3.1
