### ISSUE TITLE
Deployment of osiam.war on tomcat at Windows

### ISSUE THREAD

**Issue by tusharparate1** [osiam/osiam#266]
Hi,
Standalone deployment:
I have copied the osiam.war at tomcat webapps folder and started the server but unable to run the application by hitting http://localhost:8080/osiam.

Am I missing anything here or any setup step is missing.

Thanks,
Tushar

**Comment by dacrome** [comment]
Hi @tusharparate1,

please have a look into the [installation guide](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#starting-in-tomcat). Consider that you need a servlet container that support at least Servlet API 3.

But maybe you have just forgot to set a port, because you point to this URL: `http://localhost:/osiam` - I guess you meant `http://localhost:8080/osiam`.

Greetz,
David

**Comment by tusharparate1** [comment]
Hi David,
I have followed the installation guide from https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#starting-in-tomcat from section: Starting in Tomcat
I am trying to install on Tomcat 856 (OS: Windows).
Still I am not able to get http://localhost:8080/osiam
The application(osiam) seems to be deployed and running (seen at App Manager)
Thanks,
Tushar

**Comment by dacrome** [comment]
Hi @tusharparate1,

it's quite difficult for me to understand why OSIAM is not started, when you do not post more information. As a first step you can check the tomcat logs and post them here. But maybe you check [the whole installation process](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md), in particular the initialization of the [home directory](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#the-home-directory). It is not enough to follow the steps described in the [Starting in Tomcat](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#starting-in-tomcat) section. You need to configure OSIAM first, like the installation process described. 

Hope this helps,
David

**Comment by tusharparate1** [comment]
Tomcat Logs:
14-Oct-2016 12:17:34.425 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
14-Oct-2016 12:17:34.848 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
14-Oct-2016 12:17:34.848 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
14-Oct-2016 12:27:46.588 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
14-Oct-2016 12:27:47.009 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
14-Oct-2016 12:27:47.009 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
14-Oct-2016 12:28:56.562 INFO [http-nio-8080-exec-11] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
14-Oct-2016 12:29:19.596 INFO [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
14-Oct-2016 12:31:47.218 INFO [http-nio-8080-exec-13] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath

Catalina Logs:
14-Oct-2016 12:31:47.229 INFO [http-nio-8080-exec-13] org.apache.catalina.core.StandardContext.reload Reloading Context with name [/osiam] is completed
14-Oct-2016 12:31:47.336 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.webresources.Cache.backgroundProcess The background cache eviction process was unable to free [10] percent of the cache for Context [/osiam] - consider increasing the maximum size of the cache. After eviction approximately [10,041] KB of data remained in the cache.

**Comment by tusharparate1** [comment]
Actually my plan to take out the SCIM related jar out from OSIAM.war file and integrated with my application with oracle database and try few of the SCIM supported operation. 
So hope this is possible or do you have steps defined to integrated only SCIM from OSIAM application with oracle databases?

Thanks,
Tushar

**Comment by dacrome** [comment]
Hey @tusharparate1 

your last question is out of this scope of this issue. Please create a new one.
I think you solved the problem why you opened this issue? If you have still troubles to run OSIAM, please reopen this issue.

Greetz,
David
