### ISSUE TITLE
Separate out SCIM related code and make it independent

### ISSUE THREAD

**Issue by tusharparate1** [osiam/osiam#269]
Hi MIT Team,
Here is the just a thought to make it better the SCIM implementations:
1. Separate out the SCIM implementation from the application. Currently it is tightly coupled with sprint framework and Database. 
2. Publish only SCIM-OSIAM jar file. If we can expose the interfaces and consumer can implement those interface and provide their own implementation for database support. This will help any consumer of SCIM-OSIAM to integrate easily with their application. Currently there is OSIAM.WAR available and consumer do not want to install the application and integrate it as it involves third party jar approval and duplicate jars issues etc
3. Not sure OSIAM.war works without OAuth? Why I am saying this as we have already implemented our own OAuth server and want to use ours.
4. Support of various databases ex: Oracle database

Thanks,
Tushar

**Comment by tkrille** [comment]
Hello @tusharparate1,

> 1. Separate out the SCIM implementation from the application. Currently it is tightly coupled with sprint framework and Database. 
> 2. Publish only SCIM-OSIAM jar file. If we can expose the interfaces and consumer can implement those interface and provide their own implementation for database support. This will help any consumer of SCIM-OSIAM to integrate easily with their application. Currently there is OSIAM.WAR available and consumer do not want to install the application and integrate it as it involves third party jar approval and duplicate jars issues etc

I think this is the same suggestion that @Vindulamj already made in https://github.com/osiam/osiam/issues/256. I'm marking this as a duplicate for now.

> 1. Not sure OSIAM.war works without OAuth? Why I am saying this as we have already implemented our own OAuth server and want to use ours.

No, it doesn't. OSIAM is intended to be a complete IAM solution. But this could be subject to change, if enough users want to do their own auth outside of OSIAM. Please create a separate issue for this, so we can track user feedback and progress.

> 1. Support of various databases ex: Oracle database

In fact, OSIAM does (virtually) support any database you want. You just have to set a new vendor identifier and provide some Flyway migrations on the command line, that are tailored to the specific database. If you need more details on this, please create a separate issue and ask how to do this there.

As aforementioned, I'm closing this as duplicated by https://github.com/osiam/osiam/issues/256
