### ISSUE TITLE
Update README regarding Website

### ISSUE THREAD

**Issue by fwilhe** [osiam/osiam#27]
The README states 

> For additional information visit our official website https://www.osiam.org.

But osiam.org redirects to this project at the moment. I think this is ok if we will have a new website soon, but if not, we should delete this sentence.

What do you think, @tkrille, @dacrome, @wallner?

**Comment by wallner** [comment]
I agree, remove it.

Florian Wilhelm notifications@github.com schrieb am Mi., 19. Aug. 2015 um
15:04 Uhr:

**Comment by dacrome** [comment]
:+1:
