### ISSUE TITLE
Distribution of latest OSIAM build is broken

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#283]
We currently distribute the latest master builds via Bintray using the static file name `osiam-latest.war`. Unfortunately, Bintray only permits overwriting a released artifact during the first 180 days after the initial release [1]. This currently leads to the situation, that we cannot distribute this artifact and, even worse, our builds are broken. While we could easily mitigate the second one, fixing the distribution seems much harder. Does anyone have any thoughts or ideas on this?

**Update:** This only affects the artifact `osiam-latest` in the `downloads` repository. Artifacts in the Maven repository are fine.

[1] https://bintray.com/docs/api/#_upload_content

**Comment by tkrille** [comment]
We should clarify one thing beforehand: Do we really need this distribution artifact? Don't get me wrong, I'm neither against nor for it, but I think we should give this question some thought.

**Comment by tkrille** [comment]
We're obviously trying to do something, that isn't supported by Bintray. Maybe we are doing The Wrong Thing™?

**Comment by tkrille** [comment]
I think we have only two options:

1. Stop publishing the latest build
2. Use a different version for each latest build

Regarding 1. "Stop publishing the latest build": We don't really use the latest build for anything, but we maintain 3 links to it:

* http://osiam.github.io/2016/06/09/pre-release-osiam-3.0.CR1.html
* https://github.com/osiam/osiam#snapshots
* https://github.com/osiam/osiam/blob/master/CHANGELOG.md#changes-1 (the last entry)

Fortunately they are easy to remove and we could announce, that we stop to publish the latest build, on the blog and in the changelog. I've looked into the [download statistics](https://bintray.com/osiam/downloads/osiam/latest#statistics). The artifact was downloaded 4 times withing the last 30 days. It's not really the most wanted thing. One could also argue, whether it's more appropriate to build OSIAM yourself from the latest sources. If someone wants to use a snapshot version, they could build it themselves. They just need the JDK installed.

Regarding "2. Use a different version for each latest build": Same stuff applies regarding the 3 links we maintain. We would also announce the new way to get a snapshot on the blog and in the changelog. I propose that we create a new generic repository on Bintray called _snapshots_ or _latest_. This way the _downloads_ repository doesn't get polluted with all the snapshot versions. I'd say we use the following version pattern: `{Short Git commit id}-{Maven like timestamp, i.e. the output of "date --utc +%Y%m%d.%H%M%S"}`. This would look something like this: `102d1b8-20170114.201729`. I've created this using the the command `echo "$(git rev-parse --short HEAD)-$(date --utc +%Y%m%d.%H%M%S)"`.

**Comment by dacrome** [comment]
We can also do it like https://github.com/angular/bower-angular-route/releases and add a (snapshot) release with every build to GitHub instead of Bintray...

**Comment by tkrille** [comment]
@dacrome No I would not do this. First of all, it's more or less what I proposed in option 2., except it uses GitHub instead of Bintray for file storage. But there are several downsides with this approach:

* We have to create a tag for each build
* Creating the tag isn't enough, we still have to upload the artifact to GitHub
* We have another file storage service and our infrastructure's complexity increases

IMO creating a tag for each build is something we should not do.

**Comment by wallner** [comment]
I agree with @tkrille here, creating a tag for every build is not a good idea. Here is my suggestion: since our velocity is not that high at the moment, we could push `osiam-latest-<date>` to bintray. That would work, at least for now.

**Comment by tkrille** [comment]
We had a real life meeting and decided to stop publishing the latest build in the generic download repository at Bintray. The actual doing is described in issue #284.
