### ISSUE TITLE
osiam.org is not working

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#288]
Loading the site leads to a timeout. I think it's supposed to redirect to http://osiam.github.io/.

![screenshot from 2017-03-08 09-42-30](https://cloud.githubusercontent.com/assets/5213491/23696352/9ab2f880-03e3-11e7-970a-c5578467b381.png)

**Comment by wallner** [comment]
This was fixed earlier this week.

**Comment by tkrille** [comment]
Thank you!
