### ISSUE TITLE
Error when used SCIM:Extension

### ISSUE THREAD

**Issue by tusharparatemsi** [osiam/osiam#291]
Hi Team,
I am using following payload for my OSIAM-SCIM user provisioning to create org.osiam.resources.scim.User object using following API:
User user = mapper.readValue(json, User.class);
But I am getting error (error at the end)
json payload:
{  
   "schemas":[  
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
   ],
   "userName":"scimUser30M2",
   "externalId":"scimUser30M2",
   "name":{  
      "formatted":"Ms. Barbara J Jensen III",
      "familyName":"Jensen",
      "givenName":"Barbara"
   },
   "phoneNumbers":[  
      {  
         "value":"555-555-8377",
         "type":"work"
      }
   ],
   "emails":[  
      {  
         "value":"bjensen@example.com",
         "type":"work",
         "primary":true
      }
   ],
	"userType": "Contractor",
	"title": "Tour Guide",
	"preferredLanguage":"en-US",
	"locale": "en-US",
	"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{
		"keyString":"example",
		"keyBoolean":true,
		"keyInteger":123,
		"keyDecimal":123.456,
		"keyBinary":"ZXhhbXBsZQ==",
		"keyReference":"https://example.com/Users/28",
		"keyDateTime":"2011-08-01T18:29:49.000Z"
	}
}

ERROR:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" (class org.osiam.resources.scim.User), not marked as ignorable (25 known properties: "photos", "addresses", "meta", "externalId", "name", "displayName", "nickName", "ims", "schemas", "groups", "userName", "emails", "title", "preferredLanguage", "locale", "id", "phoneNumbers", "roles", "x509Certificates", "userType", "profileUrl", "timezone", "password", "active", "entitlements"])
 at [Source: {  
   "schemas":[  
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
   ],
   "userName":"scimUser30M2",
   "externalId":"scimUser30M2",
   "name":{  
      "formatted":"Ms. Barbara J Jensen III",
      "familyName":"Jensen",
      "givenName":"Barbara"
   },
   "phoneNumbers":[  
      {  
         "value":"555-555-8377",
         "type":"work"
      }
   ],
   "emails":[  
      {  
         "value":"bjensen@example.com",
         "type":"work",
         "primary":true
      }
   ],
	"userType": "Contractor",
	"title": "Tour Guide",
	"preferredLanguage":"en-US",
	"locale": "en-US",
	"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{
		"keyString":"example",
		"keyBoolean":true,
		"keyInteger":123,
		"keyDecimal":123.456,
		"keyBinary":"ZXhhbXBsZQ==",
		"keyReference":"https://example.com/Users/28",
		"keyDateTime":"2011-08-01T18:29:49.000Z"
	}
}; line: 30, column: 64] (through reference chain: org.osiam.resources.scim.User["urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"])

**Comment by tusharparatemsi** [comment]
Solved the issue using UserDeserializer. 
Please close this. 
Thanks.

**Comment by tkrille** [comment]
Alright, I just wanted to propose the exact same solution. I'm glad you figured it out by yourself.
