### ISSUE TITLE
Do we have org.osiam: scim-schema compatible for above Java 1.5

### ISSUE THREAD

**Issue by tusharparatemsi** [osiam/osiam#295]
Hi Team,
We are implementing the OSIAM SCIM protocol for our products which is on JDK 1.6.
I have downloaded the latest OSIAM SCIM schema jar from Maven link: https://mvnrepository.com/artifact/org.osiam/scim-schema/1.6.
But looks like the OSIAM schema available on Maven is compatible with JDK 1.7.

Do we have schema jar available which is compatible for above JDK 1.5 version.

Thanks,
Tushar.

**Comment by tkrille** [comment]
Hello @tusharparatemsi,

first of all, you're right: the `scim-schema` artifact is build with a target version of Java 1.7. So, to answer your question, there is no `scim-schema` available, that runs on Java 1.6. Please be aware that we deprecated the `scim-schema` for various reasons found [here](https://github.com/osiam/osiam/issues/197#issuecomment-201086938). This means that we don't support this artifact anymore and there will be no future releases.

**Comment by tkrille** [comment]
I'm closing this for now. If you have further questions, feel free to open this issue again, @tusharparatemsi.
