### ISSUE TITLE
Evaluate Migration Path from Maven to Gradle

### ISSUE THREAD

**Issue by fwilhe** [osiam/osiam#30]
As osiam/shell#14 shows, migrating from Maven to Gradle is not as straight-forward as it seems. 

The [init plugin](https://docs.gradle.org/current/userguide/build_init_plugin.html) (that can be used like so)

```
gradle init --type pom
```

is useful, but does not convert everything in the pom to Gradle.

My plan is to work out an example migration for the shell project and document the steps, so that other projects can benefit from the lessons learned.

**Comment by dacrome** [comment]
I created a doing issue: https://github.com/osiam/osiam/issues/257
