### ISSUE TITLE
Which Service for Artifact Distribution?

### ISSUE THREAD

**Issue by fwilhe** [osiam/osiam#31]
This issue formalizes the discussion we had about which service to choose for distribution OSIAM artifacts. I heard of [bintray](https://bintray.com/) and [sonatype](http://central.sonatype.org/).

I personally never used any of them, so I don't have a personal preference.

This is related to #30, since we are looking for a Gradle plugin for publishing artifacts.

**Comment by fwilhe** [comment]
@wallner expressed that he is in favor of bintray.

What do @dacrome and @tkrille think?

This issue is a blocker for #30

**Comment by tkrille** [comment]
I'm in favor of Sonatype's snapshot repository. There's no real rationale behind this, except that we already have an account at Sonatype.

**Comment by dacrome** [comment]
Which service is easier to setup (release-plugin, token management, API, Web UI, ...) except the fact that we already have a sonatype account? Any benefits of using bintray instead of sonatype? Pro/contra?

**Comment by fwilhe** [comment]
> Which service is easier to setup

An example for bintray is at osiam/shell#16. I have no idea about sonatype, never used it before.

**Comment by wallner** [comment]
Bintray is ridiculously easy to set up. I still think we should go for that. Especially since we get a lot additional features out of it.

**Comment by dacrome** [comment]
Which additional features?

**Comment by tkrille** [comment]
The snapshot repository at Sonatype is just ja normal Maven repo (it's backed by Sonatype's Nexus). So the normal Maven deployment process applies, [that is also supported by Gradle](https://docs.gradle.org/current/userguide/publishing_maven.html). There's also a specialized plugin available: https://github.com/bmuschko/gradle-nexus-plugin. On the other hand, Bintray looks really promising. But I don't think it offers more or less features than Sonatype.

Important to me is, that we only use one of them for the distribution of snapshots and releases. So, the only point in favor of Sonatype is, that we already use it and won't have to migrate the release process to Bintray.

**Comment by tkrille** [comment]
Seems like, that Bintray can automatically sign artifacts for us. That would be really nice to have!

**Comment by tkrille** [comment]
Alright, it's voting time. You can choose between:

A) Sonatype

B) Bintray

**Comment by tkrille** [comment]
B

**Comment by dacrome** [comment]
B, because of the automatically signing of artifacts, greater feature set and the better UI

**Comment by fwilhe** [comment]
B

**Comment by wallner** [comment]
B

**Comment by tkrille** [comment]
Alright, Bintray it is.
