### ISSUE TITLE
Using the License Maven Plugin

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#33]
To make sure that all files in the repos have an update-to-date license header, we should use the [`License Maven Plugin`](http://www.mojohaus.org/license-maven-plugin/).

**Comment by tkrille** [comment]
We already have gained some experience with that in another project. It works very well and frees us from some manual work. On the other hand: we're currently think about migrating to Gradle, which would make this issue kinda obsolete.

**Comment by fwilhe** [comment]
> repos have an update-to-date license header

Is this really an issue? Who cares about what date is written in the copyright declaration?

> migrating to Gradle

Looks like [something like that](https://github.com/hierynomus/license-gradle-plugin) exists for gradle.

**Comment by fwilhe** [comment]
After trying the gradle plugin, I think it works quite well. We could really go for that, IMHO.

`./gradlew licenseFormat` will add license hints to all java files, `./gradlew check` includes a check for the licenses when the plugin is applied. `./gradlew downloadLicenses` can generate reports on licenses of 3rd party libraries. Works like a charm.

**Comment by fwilhe** [comment]
I suggest using the gradle plugin like in osiam/shell#20 for this issue globally for the OSIAM-project and to close this issue hereby. What do you think about that, @wallner, @dacrome, @tkrille?

**Comment by wallner** [comment]
That would imply that we moved all projects to gradle, as suggested in #30. As long as we haven't done that, we should consider using the [license maven plugin](http://www.mojohaus.org/license-maven-plugin/)

**Comment by dacrome** [comment]
Reopened, because it's closed with a wrong issue link in a commit message of the PR #44
