### ISSUE TITLE
Migrate to BCrypt hashes.

### ISSUE THREAD

**Issue by wallner** [osiam/osiam#34]
Spring Security deprecated the `PasswordEncoder` interface for quite some time now. I suggest that we migrate the used password encoder to an BCrypt implementation. We should do that in two steps:
1. Provide our own implementation of a `PasswordEncoder` that proxies calls to the `isPaswordValid()` method and updates the password field in the database with the newly encrypted password on successful login.
2. Announce that we are going to lock out all users with the old password field after two releases (or a yet undefined length of time)
3. Replace our proxy implementation with the actual `BcryptEncoder` implementation after a clearly communicated grace period and a later release. The Flyway database migration for that release should lock all users that still use the old hashing method.

So, what do you think?

**Comment by tkrille** [comment]
Sounds viable, but I think Step 1. will be more complicated than you've described it. AFAIK we never call `PasswordEncoder.isPaswordValid()` but start a search on the resource server for all users that have the supplied username and hashed password. So updating the password during a login must be done in the domain layer within the auth-server, whereas hashing passwords and storing them is done in the resource-server.

**Comment by dacrome** [comment]
Thanks @wallner for breaking this down. Yes, in `auth-server` we make a [search on username and hashed password](https://github.com/osiam/auth-server/blob/1650e7a7152e8a27823af0a5042774601945367e/src/main/java/org/osiam/auth/login/internal/InternalAuthenticationProvider.java#L106).
1. `auth-server`: I don't think we need to provide our own implementation, just create a second password encoder Bean, I guess [`BCryptPasswordEncoder`](http://docs.spring.io/autorepo/docs/spring-security/4.0.2.RELEASE/apidocs/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.html). But we need to make two searches with the different hashed password. First search should be with the new hashed password, if no user existing search with the username and the old hashed password. Then replace the user with the raw password, but in the  `resource-server` the old [password encoder needs to be replaced](https://github.com/osiam/resource-server/blob/695951b0e6014f22e2590c3caf40f48b970b319a/src/main/java/org/osiam/ResourceServer.java#L111) with the `BCryptPasswordEncoder`. So if a new user will be [created](https://github.com/osiam/resource-server/blob/695951b0e6014f22e2590c3caf40f48b970b319a/src/main/java/org/osiam/resources/provisioning/SCIMUserProvisioning.java#L98) or an existing one will be [replaced](https://github.com/osiam/resource-server/blob/695951b0e6014f22e2590c3caf40f48b970b319a/src/main/java/org/osiam/resources/provisioning/SCIMUserProvisioning.java#L128), the new hashed password will be stored.
2. Ok, but maybe we should provide in `addon-self-administration` a password forget mechanism, if some users didn't logged-in in the defined time.
3. +1 for the Flyway database migration

**Comment by tkrille** [comment]
Should we schedule this for 3.0?

**Comment by dacrome** [comment]
Yes. Here are my drafts: [auth-server](https://github.com/osiam/auth-server/compare/master...dacrome:new-password-encoder?expand=1) and [resource-server](https://github.com/osiam/resource-server/compare/osiam:master...dacrome:new-password-encoder?expand=1)

**Comment by tkrille** [comment]
Does this mean we have to change all database seeds in the ITs, etc.?

**Comment by wallner** [comment]
I like the drafts. @tkrille yes. we will need to do that.

**Comment by dacrome** [comment]
Reopened, because it's closed with a wrong issue link in a commit message of the PR #44
