### ISSUE TITLE
Make it very clear in the documentation that it is recommended to run OSIAM over HTTPS

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#39]
As discussed in osiam/osiam#12, we want to explicitly state in the documentation, that OSIAM should always be used with HTTPS. Maybe we should give some some advice on how to do that, too.

**Comment by tkrille** [comment]
Is [this](https://github.com/osiam/osiam/blame/4745cafee0ad6f9637b413333d07b353f717f019/docs/detailed-reference-installation.md#L44) already enough?

**Comment by wallner** [comment]
Yes.
