### ISSUE TITLE
Code-Style for Logger

### ISSUE THREAD

**Issue by fwilhe** [osiam/osiam#40]
Based on osiam/resource-server#80, we had an informal discussion about the naming for loggers.

The discussed options are:
- `LOGGER` (This is the current state in the OSIAM codebase, and IDEs will suggest such names for `static final` variables, because this is how constants are declared in java)
- `LOG`
- `logger`

For comparison, consider how the calls would look like:

``` java
// 1
LOGGER.warn("foo");
// 2
LOG.warn("foo");
// 3
logger.warn("foo");
```

(I did not hear another option until now, feel free to add, if you have one in mind)

I personally would prefer `logger` because although the field is `static final`, it is not a "constant".

This issue contains two tasks:
- Make an decision on how we want to have the style
- (If we decide to not use `LOGGER`): Make the change in the whole OSIAM codebase.

**Comment by wallner** [comment]
My favorite is 3.

**Comment by tkrille** [comment]
``` java
// 4
log.warn("foo");
```

My favorite is 4 :)

**Comment by dacrome** [comment]
My favorite is 4

**Comment by fwilhe** [comment]
Since @osiam-ci is not permitted to vote (I'm looking at you, @dacrome ;-), we have a tie.

I'm not so sure. I don't like such abbreviations.

`log` can mean so many things. Is it a logarithm? Well, I admit that this particular mistake is really not likely provided the context, but still I prefer to remove the mental overhead that the abbreviation introduces.

How do we proceed? Is anyone willing to switch and break the tie?

**Comment by tkrille** [comment]
Should we flip a coin?

**Comment by dacrome** [comment]
alea iacta est: `logger`
