### ISSUE TITLE
Merge the core services

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#43]
Unfortunately, splitting the auth- and resource-server didn't really work out. Especially in view of the migration to a standalone application (#5), it makes sense to just have 1 artifact. Other reasons are:
- The communication between auth- and resource-server increases the overall complexity and introduces a bottleneck within the system
- Both services are tightly coupled by design, leaving a split questionable
- The core OSIAM services should feel like "one thing" not a distributed system in itself
- Versioning is sometimes confusing
- Building, testing and deploying is more complex than necessary
- Documentation, issues and other information is scattered across multiple repos
- Migration to BCrypt hashes becomes possible

This list makes no claims of being complete.

I'd also suggest, that we merge the functionality of addon-self-administration and addon-administration into the core, too. But I would leave that for the future.

As splitting once had a use case, namely operating the user-facing auth-server part on a public interface, but hide the resource-server part in a private network, we should think about
1. whether we still want to support this use case
2. how we want to implement it

To answer 1.: I don't think so. After all, controlling access is OSIAM's business, so there should be no harm in having the resource-server's endpoint publicly available. They're secured with OAuth anyway. I'm also not aware of that anyone is operating OSIAM like this. One can still simulate this "feature" by putting OSIAM in a private network and reverse proxying just the auth-server endpoints, or something like that.

We should put this on the 3.0 Roadmap, as it is a major breaking change.

**Comment by tkrille** [comment]
I've started to implement this (https://github.com/tkrille/osiam-osiam/tree/merge-servers), but have a question:

Should we remove the creation of data (admin user, example-client, etc.) from the Flyway migrations and rather create them on the first start, i.e. when no data is contained in the database. Remember, we can now have a fresh start of this.

**Comment by wallner** [comment]
I like your work on that very much and fully agree with you on all the points raised. Thank you for working on it. I like the idea of getting rid of using flyway to initially creating data and move that to the first start of the application.

**Comment by dacrome** [comment]
I also like your work and mostly agree.

One point is missing:
When the auth- and resource-server are merged, we can [migrate to BCrypt hashes](34).

> I'd also suggest, that we merge the functionality of addon-self-administration and addon-administration into the core, too. But I would leave that for the future.

I don't think that's a good idea, but like you said, let's discuss this later.

> Should we remove the creation of data (admin user, example-client, etc.) from the Flyway migrations and rather create them on the first start, i.e. when no data is contained in the database.

Yes, good idea. Later we should make this configurable. Maybe just switch it on or off or make the data configurable via yaml. I think the use case is that a customer wants an easy customization of the data within they install process.

**Comment by tkrille** [comment]
> When the auth- and resource-server are merged, we can migrate to BCrypt hashes.

I've incorporated this in my description, thanks.

Ok, then we remove the creation of example data via Flyway. I'll create a separate issue for this.
