### ISSUE TITLE
Check exception handling

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#48]
The merge caused the exception handling to change. Instead of 1 exception handler for all controllers, we now have 2 for specific controllers. One exception handler processes faults from the REST resources and always returns JSON. The other processes all faults from the web resources, i.e. HTML pages, and returns the default OAuth error view. It also only contains a handler for `Exception.class`.

The problems with that are:
- Faults from `@FrameworkEndpoint`s will not be handled anymore by our exception handler, but will trigger the whitelabel error page included with Spring Boot
- Both handlers are responsible for handling `Exception.class`, which already led to issues on different machines (https://github.com/osiam/osiam/pull/44#issuecomment-150341982)
- The distinction between web and REST resources is not fully implemented. For example, some RESTful resources like token validation will be handled by the web exception handler, though they always respond with JSON.

So, we have to find a solution for this.

**Comment by tkrille** [comment]
> Faults from @FrameworkEndpoints will not be handled anymore by our exception handler, but will trigger the whitelabel error page included with Spring Boot

I've checked this point and, fortunately, we already implement [`/oauth/error`](https://github.com/osiam/osiam/blob/master/src/main/java/org/osiam/security/controller/AccessConfirmationController.java#L71). So, no worries here. I've also actually tested that errors from `/oauth/authorize` lead to the well-know error screen:

![oauth_error](https://cloud.githubusercontent.com/assets/5213491/15835419/2d9aa44a-2c30-11e6-99b8-ce667bfb60d5.png)

Maybe we change this in the future ... :)

**Comment by tkrille** [comment]
> Both handlers are responsible for handling Exception.class, which already led to issues on different machines

This should be no problem anymore, because responsibility of the exception handler has been restricted.

**Comment by dacrome** [comment]
So what is the concrete doing here? Seperation of web and rest controller exception handler?

**Comment by tkrille** [comment]
> The distinction between web and REST resources is not fully implemented. For example, some RESTful resources like token validation will be handled by the web exception handler, though they always respond with JSON.

See #225

**Comment by tkrille** [comment]
@dacrome I've already done it :)

**Comment by dacrome** [comment]
;)

**Comment by tkrille** [comment]
You wanna review #225? :)
