### ISSUE TITLE
Deploy to Bintray snapshots with CircleCI

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#59]

**Comment by dacrome** [comment]
I think we should create a `circleci` repository to share the same `settings.xml` like [alexec did](https://github.com/alexec/circleci). What do you think?

**Comment by dacrome** [comment]
And should we create a maven profile `snapshots` for deploying the snapshots to OJO?

**Comment by wallner** [comment]
Please no profile.They only wreak havoc on builds.

**Comment by dacrome** [comment]
> Please no profile.They only wreak havoc on builds. 

Ok, then I specify an oss.jfrog snapshots `distributionManagement` element in the poms and the deployment can by done with `mvn deploy` (or `mvn deploy -s settings.xml` on CircleCI) with the correct Bintray username and password (Bintray API Key). But how do we differ from a release deployment? Because I thought about to create a `snapshots` and `release` maven profile.

**Comment by dacrome** [comment]
> I think we should create a circleci repository to share the same settings.xml

I created a [general maven settings file in the circleci repository](https://github.com/osiam/circleci/pull/1) which can be pulled on circleci after a changed master branch.
