### ISSUE TITLE
Spring Boot: Which default ports should we use?

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#6]
We want to migrate all OSIAM backend components to Spring Boot. Because all components will be started as standalone applications, we should think about default ports. I already created an [issue for the self-administration](https://github.com/osiam/addon-self-administration/issues/120). But the port selection is necessary for all OSIAM backend components, so I created this issue to sync which port we choose for every component.

@tkrille already [made a suggestion](https://github.com/osiam/addon-self-administration/issues/120#issuecomment-104557653): Port range from 50511 to 50514. The ports are for sure configurable, but we should provide the applications with default ports.

That would mean:

| component | server port | admin port |
| --- | --- | --- |
| auth-server | 50511 | 51511 |
| resource-server | 50512 | 51512 |
| self-administration | 50513 | 51513 |
| administration | 50514 | 51514 |

Ok?

**Comment by tkrille** [comment]
I also made the recommendation to **NOT** use distinct "admin ports", but secure these interfaces with OAuth and scope `ADMIN` (coming up soon).

**Comment by tkrille** [comment]
I'm pretty fine with the port mappings. @dacrome Is it possible to configure at runtime, whether one single port is used or two distinct ports for public and administrative resources?

**Comment by wallner** [comment]
I think it would be a good thing if we could completely do without admin ports. Let's expose the admin functionality on protected resources. After all that's what OSIAM is made for, we should eat our own dog food.

**Comment by tkrille** [comment]
I think it's time to settle on something. I'm fine with the ports, but I don't think we should support admin ports in the default configuration.

> @dacrome Is it possible to configure at runtime, whether one single port is used or two distinct ports for public and administrative resources?

You got an answer on that for me @dacrome? :)

**Comment by dacrome** [comment]
> You got an answer on that for me @dacrome? :)

By default the actuactor endpoints are [exposed over the same port](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html). Really nice is the possibility to customize the context path. But we should discuss everything about actuator/metrics/monitoring in the [already created issue](https://github.com/osiam/osiam/issues/8).

So if everyone is fine with the ports, we can close this issue and use them when switching to fat jars :)

**Comment by tkrille** [comment]
So we completely discard the admin ports?

**Comment by tkrille** [comment]
We'll stick with the default port of 8080.
