### ISSUE TITLE
Resources with only 'primary' sub-attribute set should be rejected

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#62]
Moved from https://github.com/osiam/resource-server/issues/10:

Currently it is possible to create a user with multi-valued attributes where only the sub-attribute 'primary' is set. This should not be possible, a multi-valued attribute should only be valid if at least one of the sub-attributes are set that needed for the identification of the resource.

**Comment by wallner** [comment]
We would like to fix this bug for 3.0, although it's low priority.
