### ISSUE TITLE
Build Debian packages in this repo

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#64]
Moved from https://github.com/osiam/resource-server/issues/16:

This repo should contain stuff so that a Debian package can be build. It's still open whether we should use vanilla Debian packaging scripts and stuff, or maybe use the excellent [pkg-maven-plugin](https://github.com/tarent/pkg-maven-plugin). I would recommend the [pkg-maven-plugin](https://github.com/tarent/pkg-maven-plugin).

**Comment by dacrome** [comment]
Please also check the discussion in the old issue.

**Comment by dacrome** [comment]
Sorry, my fault

**Comment by tkrille** [comment]
That's not going to happen.
