### ISSUE TITLE
Search filter cuts string query, when using not supported operator and fired no exception

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#66]
Moved from https://github.com/osiam/resource-server/issues/32:

> When using = instead of eq in the string filter with the OsiamConnector, the filter string will be cut and no exception fired.
> 
> Right filter string:
> "userName eq \"user1\" and name.formatted eq \"formatted1\""
> -> both constraints will be used
> 
> Wrong filter strings:
> "userName eg \"user1\" and name.formatted = \"formatted1\""
> -> just uses the first constraint, the second will be cut
> 
> "userName = \"user1\" and name.formatted = \"formatted1\""
> -> exception fired: org.osiam.client.exception.ConflictException: no viable alternative at input 'userName"user1"'

You can actually see that ANTLR complains about the wrong operator in the server logs. Seems that the message is put on STDOUT or STDERR.

**Comment by wallner** [comment]
The correct behaviour when receiving a wrong query should be to generate a 400 BAD REQUEST.
