### ISSUE TITLE
Switch to standalone application

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#71]
Moved from https://github.com/osiam/resource-server/issues/45 & https://github.com/osiam/auth-server/issues/25:

After switch to Spring Boot fat war has been solved (it is!), we can move on with the [plan](https://github.com/osiam/osiam/issues/5) and finally switch to a standalone, runnable `.jar` deployment. This does not contain switching to YAML files, which will be done in a separate step.

**Comment by tkrille** [comment]
This won't happen.
