### ISSUE TITLE
Make Prototype for spring-restdocs

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#75]
Moved from https://github.com/osiam/resource-server/issues/82:

@sputnik27 wrote:

> As discussed in osiam/osiam#29, we should write some REST-API docs using [spring-restdocs](https://github.com/spring-projects/spring-restdocs) to get a clear impression on it's capabilities. The `resource-server` should be a good place to start, I think.

**Comment by fwilhe** [comment]
I started looking into this again, on this branch: https://github.com/fwilhe/osiam/tree/spring-restdocs

Still experimenting, so I can't tell when I will open a PR.

**Comment by tkrille** [comment]
Spring Rest Docs seems to be agreed upon. An evaluation is not necessary anymore.
