### ISSUE TITLE
Destroy all user http sessions if all user tokens will be revoked

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#77]
Moved from https://github.com/osiam/auth-server/issues/11:

@dacrome wrote:
In a single application use case it makes sense to trigger a global user logout by revoke all tokens and simultaneously destroy all http sessions on the auth-server. This can be done by adding the destruction of the http sessions if [all user tokens will be revoked](https://github.com/osiam/osiam/blob/4745cafee0ad6f9637b413333d07b353f717f019/src/main/java/org/osiam/security/controller/TokenController.java#L61#L61).

**Comment by tkrille** [comment]
We should rather add a `/logout` endpoint.

**Comment by tkrille** [comment]
As we will migrate to JWT, this issue is obsolete.
