### ISSUE TITLE
Monitoring of the OSIAM components

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#8]
We should provide monitoring and metrics via the [Spring Boot Actuator](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready) for all OSIAM backend components. For sure this can only be done, if the components are migrated to Spring Boot.

**Comment by tkrille** [comment]
+1

**Comment by tkrille** [comment]
Let's create the appropriate issues once the Boot'ification is complete.

**Comment by dacrome** [comment]
We should also use the possibility to provide [custom application information](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info) e.g. the OSIAM version which was already a feature request in [auth-server](https://github.com/osiam/auth-server/issues/88) and [resource-server](https://github.com/osiam/resource-server/issues/100)

**Comment by tkrille** [comment]
Yes, sounds good. But how do we get the current version into the `application.yaml` file?

**Comment by dacrome** [comment]
Yes, that's a good question. Maybe by maven within the build process?

**Comment by tkrille** [comment]
Don't we put the version already in the manifest file? I thought it will be read from there by Spring Actuator.

**Comment by dacrome** [comment]
[Actuator can read from the pom](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-automatic-expansion-maven)

**Comment by tkrille** [comment]
Alright, then we do it like this.

**Comment by tkrille** [comment]
I don't think we need to create more issues for this topic. Let's just add actuator und configure everything appropriately: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready

**Comment by tkrille** [comment]
I've put this into 3.1

**Comment by dacrome** [comment]
Yes. But we should not forget to make the management port configurable (`osiam.admin.port`?) and the endpoints need to be secured. Maybe also a config to switch it on or off?

**Comment by tkrille** [comment]
> But we should not forget to make the management port configurable (osiam.admin.port?)

I thought we don't want to use an admin port, but secure the endpoints with, well, OSIAM :)

**Comment by tkrille** [comment]
> Maybe also a config to switch it on or off?

I don't think we should make this feature "toggleable". Who would switch monitoring off?

**Comment by dacrome** [comment]
> I thought we don't want to use an admin port, but secure the endpoints with, well, OSIAM :)

For sure with OSIAM :)

> I don't think we should make this feature "toggleable". Who would switch monitoring off?

Nope.
