### ISSUE TITLE
Store tokens in the database

### ISSUE THREAD

**Issue by dacrome** [osiam/osiam#80]
Moved from https://github.com/osiam/auth-server/issues/61:

@tkrille:

Currently, access tokens are stored in an in-memory token store provided by Spring Security OAuth. This has some fundamental flaws, for example:
- Restarting OSIAM revokes all access tokens
- OSIAM cannot be scaled on the x-axis of the [scale cube](http://microservices.io/articles/scalecube.html)
- We leak state between the individual integration tests which leads to the unpleasant fact that they are not isolated against each other

Especially the last point has given me a hard time yesterday, when I tried to update the ITs for the removal of the old, method-based scopes.

So, I propose that we put the tokens into the database.

@dacrome:

+1. With Spring OAuth it's easy to switch the store for [managing tokens](http://projects.spring.io/spring-security-oauth/docs/oauth2.html#managing-tokens).

**Comment by tkrille** [comment]
We should rather use cryptographic tokens (JWT).

**Comment by abdelgadir** [comment]
Hi,
and speaking of JWT, do you have plans to support openid connect [which also builds on oauth2]?

**Comment by wallner** [comment]
Hello @abdelgadir,
we most definitely plan to build openid connect support, we do have it in the back log. However it is not going to be in the upcoming 3.0 release and we can't really promise a time frame.

**Comment by abdelgadir** [comment]
@wallner 
Great ! 
and thank you for this amazing software

**Comment by tkrille** [comment]
We will use JWT instead of persisting tokens in the database.
