### ISSUE TITLE
Wrong schemas in docs

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#87]
There are still some places in the docs that use the old SCIM schemas, e.g. [detailed-reference-installation.md](https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md). Must be changed to current schemas.

**Comment by tkrille** [comment]
I'm sorry, but the URNs are still not right.

**Comment by wallner** [comment]
The only urn that I can find is `urn:org.osiam.extensions:Test:1.0` which I think is perfectly fine, since it is the URN of the osiam extension, right?

**Comment by tkrille** [comment]
What about `urn:scim:schemas:core:2.0:User` in https://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md? AFAIK the right schema is `urn:ietf:params:scim:schemas:core:2.0:User`.
