### ISSUE TITLE
Wrong diagram in docs

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#9]
The "architecture diagram" under https://github.com/osiam/osiam/blob/master/docs/OSIAM-Overview.md#gateways-between-these-systems is not up-to-date and must be changed. IIRC it was initially done by @leberKleber, so one should get the source from him and update it.

@leberKleber do you remember this and could you provide the source file to us?

**Comment by tkrille** [comment]
@leberKleber ping

**Comment by tkrille** [comment]
Alright, this doesn't seem to happen. Everybody OK with just removing the diagram?

**Comment by fwilhe** [comment]
> removing the diagram?

:+1:

**Comment by dacrome** [comment]
Let me ask @leberKleber later via chat

**Comment by wallner** [comment]
To be honest the whole document needs to be updated.

**Comment by leberKleber** [comment]
Hello everybody,
unfortunately I can't find the chart.
It's too long ago.

Sorry

**Comment by dacrome** [comment]
Hey @leberKleber, thanks for the feedback. So let's remove this old diagram. Should we create a new issue to make sure a new one will be created?

**Comment by tkrille** [comment]
> Should we create a new issue to make sure a new one will be created?

Do we really need a new one?

**Comment by dacrome** [comment]
> Do we really need a new one?

No.
