### ISSUE TITLE
Give up "main" distribution, remove add-ons from core

### ISSUE THREAD

**Issue by tkrille** [osiam/osiam#93]
I'd like to suggest, that we give up the idea of an OSIAM "core" or "main" distribution. I.e. the big distribution, containing auth-server, resource-server, the add-ons, and the respective Debian packages. I think it didn't work out as expected. There are several flaws, like
- It's difficult and time- and space-consuming to provide SNAPSHOT builds of it. This prevents consumers from including the current test version and makes it impossible to simply test the current development version of OSIAM.
- All contained components are tightly coupled with respect to their release cycle.
- The Debian packages are currently not well maintained and contain known bugs.
- Putting this stuff on the GitHub release page wastes our time and GitHub's storage resources.
- There already are the single distributions, that contain the same stuff, but in multiple archives.

Offering Debian packages is still something we should strive for, but we should create them in the respective repos and not in a super repo.

In the course of this, I'd also suggest to separate the core servers from the add-ons, so that each one has it's own, independent release cycle. It's an unwritten rule, but we always release them together. This process is partly due to the existence of the big distribution.

I'd suggest to start with this procedure with OSIAM 2.5, which will then only contain auth-server 2.5 and resource-server 2.5.

PS: This is also part of making everything ready for OSIAM 3.0, of course.

**Comment by tkrille** [comment]
I think, that also means to move the self-admin ITs into the self-admin's repo or something.

**Comment by wallner** [comment]
Your suggestion is very plausible. I say we should go for it.

**Comment by fwilhe** [comment]
I agree with @wallner.

**Comment by dacrome** [comment]
Thanks for the detailed explanation. It makes totally sense. So: Go for it!

**Comment by tkrille** [comment]
Ok, I will create the necessary tasks and close this issue.

**Comment by tkrille** [comment]
I think, I've created all necessary issues and PRs. Thanks for your participation.
